sylius_grid:
    grids:
        oxyshop_sylius_badge_plugin.badge:
            driver:
                name: doctrine/orm
                options:
                    class: Oxyshop\SyliusBadgePlugin\Entity\Badge
            sorting:
                order: asc
            limits: [50, 100, 200]
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                enable:
                    type: twig
                    label: sylius.ui.enable
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                order:
                    type: string
                    label: sylius.ui.position
                    sortable: ~
                class:
                    type: string
                    label: oxyshop_sylius_badge_plugin.ui.class
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name, description, class]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
